### ISSUE TITLE
Wav to mp3 conversion

### ISSUE THREAD

**Issue by calippo** [jiaaro/pydub#100]
I am trying to convert a .wav file to a .mp3 file using pydub.
The conversion is fine, but a silence of 0.05s is constantly added to the beginning of the file.
Is there an easy way to resolve this issue?

**Comment by calippo** [comment]
Ok, I solved the issue cutting the AudioSegment as
song = song[50:]
However, why is 0.05s padding added to the beginning of the file?

**Comment by jiaaro** [comment]
@calippo most likely the padding was added by the mp3 encoder, it's common (and annoying)

**Comment by burnaz** [comment]
@calippo 
I have the same problem, can you share your code here?
Thanks

**Comment by burnaz** [comment]
@calippo How can I export a mp3 AudioSegment without this silence?
My code below:

```
from pydub import AudioSegment
sound = AudioSegment.from_mp3("sample.mp3")
sound = sound[50:]
sound.export("sample.mp3")
```

But I always have 5 ms with silence at beginning of sound. I want to split a song file to play in Android without breaks. 

I had success exporting as wav file, but I can't use wav because it's too big. Exporting .ogg file I have an interruption playing chunks files.

I apreciate your help as soon as possible. Thanks very much Jiiaro

**Comment by jiaaro** [comment]
@burnaz I'm pretty sure (especially since this does not occur with wav data) that this is caused by the codec.

Maybe try using m4a files? Apple uses those and they made a big deal out of gapless album playback a while back ¯\_(ツ)_/¯ 

ultimately, pydub doesn't handle encoding and decoding the audio files directly so we're kind of at the mercy of the codecs that ship with ffmpeg :/

**Comment by burnaz** [comment]
@jiaaro 

I tried to use m4a, but I got same result of .ogg, a little interruption like "beep" between transition.

`"sound1.export("sound-part1.m4a", format="mp4")`

Do you have any suggestion, or any codec to use?

I'm working on a project to reduce cost of audio streaming for web servers. For an example, instead of mobile applications download 5mb of a full file, download individually chunks of 150kb. So, users will download only chunks that they will listen. Besides that mobile app will have a faster navigation between songs. This project is like Spotify does in their apps.

I want to share this project on Github.

Thanks for any sugestions.

**Comment by jiaaro** [comment]
you could use wave format and use a generic compression algorithm (like gzip, or something better)

**Comment by burnaz** [comment]
@jiaaro 

I foud the problem, it was simpler than I expected.
Pydub is splitting audio putting some bad data at the end of file (in .ogg case), look the example below:

<img width="792" alt="screen shot 2016-05-12 at 10 13 55 am" src="https://cloud.githubusercontent.com/assets/7516541/15216100/1c1b2fcc-182c-11e6-9c6c-b48ea2bc7874.png">

The wave was interrupted, I tried to split a constant frequency audio file into 2 seconds files.
Do you think is better to create a new topic to discuss about it?

I appreciate the support.

**Comment by jiaaro** [comment]
@burnaz funny you should say that, just yesterday we were talking (in [another issue](https://github.com/jiaaro/pydub/issues/138#issuecomment-218396122)) about how some codecs insert silence at the beginning and end of audio.

WAV data is not affected because it is the only format pydub handles natively (it does not pass through a codec, and ffmpeg is not called – all other formats are converted to wav before being loaded into an `AudioSegment` object)

If you can find a method of encoding/decoding audio without the problem of leading and trailing silence then you can pass the raw audio data as a bytestring to the `AudioSegment()` class constructor directly:

```python
from pydub import AudioSegment

# 2 bytes == 16 bits
sample_width = 2

# 2 channels, aka stereo
channels = 2

# CD quality: 44.1kHz sample rate
frame_rate = 44100

# one frame of stereo, 16-bit silence (2 bytes per channel, left channel first)
audio_data = b"\0\0\0\0"

sound = AudioSegment(audio_data, 
    sample_width=sample_width, 
    frame_rate=frame_rate,
    channels=channels
)
```

**Comment by burnaz** [comment]
@jiaaro 

I found a solution using only ffmpeg, but I don't know yet why pydub works different.
I can be wrong, but I understood that you are thinking the problem is when pydub imports a file. The trouble is when I call method .export(), he put silence at the end of new file.

Using only ffmpeg, I don't have this problem.
`ffmpeg -- 0 -t 30 -i filme.mp3 file.ogg`

For an example, pydub works perfectly when I export to a .wav format, doesn't matter if I imported from a wav/mp3/ogg/mp4 file. The question here is only about the output format:

When using .wav it works, when using other compressed format it creates a silence at the end of file.
(We know mp3 format always have this silence at the beginning, by this way I'm not working with this format). Sorry about any possible mistake.

Now, tell me if I could help of anyway, I fixed my problem and I'd like to collaborate to help others.

Thanks again Jiaaro

**Comment by jiaaro** [comment]
@burnaz According to [this guy on superuser](http://superuser.com/a/409917) the only way to do gapless playback with mp3 encoded audio is to include metadata (like LAME does) about how much extra crap was added by the codec so you can throw it away during playback.

I think the `-t` ffmpeg option is actually just encoding chopping off the end of the file (so the encoder never gets a chance to add the padding at the end). but if it works it works :)
