### ISSUE TITLE
Support for direct access to an audiosegment's sample data

### ISSUE THREAD

**Issue by ferrouswheel** [jiaaro/pydub#116]
I was looking for a way to easily decode and play audio files with [pyaudio](http://people.csail.mit.edu/hubert/pyaudio/) while avoiding an extensive framework like pyglet/pygame.

pydub looks great and makes it simple to load mp3s and other formats, but it seems very focussed on the manipulation of audio files.

I was able to play an mp3 with pyaudio by directly accessing the `_data` member of an AudioSegment instance, as shown in the attached code snippet. I tried using an iterator, but that just generates new AudioSegments.

It'd be awesome if AudioSegment could provide a public interface to `_data` that will be supported in future versions.

```
import pyaudio
from pydub import AudioSegment

CHUNK_SIZE = 1024 * 8
song = AudioSegment.from_mp3("my.mp3")
p = pyaudio.PyAudio()

stream = p.open(format=p.get_format_from_width(song.sample_width),
                    channels=song.channels,
                    rate=song.frame_rate,
                    output=True)

for i in range(0, len(song._data) / CHUNK_SIZE):
    frames = song._data[i*CHUNK_SIZE:(i+1) * CHUNK_SIZE]
    stream.write(frames)

stream.stop_stream()
stream.close()
p.terminate()
```

**Comment by jiaaro** [comment]
Hi!

pydub 0.16.0 (released today) has some goodies you might be interested in :)

`audio_segment.raw_data` is an officially supported public API that provides access to the raw audio data as a bytestring ([docs](https://github.com/jiaaro/pydub/blob/master/API.markdown#audiosegmentraw_data)).

since that's not a very easy format to work with, there's also a new method which returns the same data as an array of (numeric) samples: `audio_segment.get_array_of_samples()` ([docs](https://github.com/jiaaro/pydub/blob/master/API.markdown#audiosegmentget_array_of_samples))

Finally, pydub does come with a simple playback example for use in debugging ([code here](https://github.com/jiaaro/pydub/blob/master/pydub/playback.py)), that might be helpful to anyone finding this ticket through search:

```python
from pydub import AudioSegment
from pydub.playback import play

sound = AudioSegment.from_file("/path/to/sound.wav")

# uses pyaudio if available, falls back to opening an ffplay subprocess
play(sound)
```

**Comment by ferrouswheel** [comment]
This is great - thank you!

**Comment by tcarroll2** [comment]
THIS!!!  Thank you!  I read that, but I did not understand the ramifications of that little function.  This is going to allow me to complete my project!  Thank you, very much!!!
