### ISSUE TITLE
reduce volume of audio file in python

### ISSUE THREAD

**Issue by great-thoughts** [jiaaro/pydub#144]
I am using this code to reduce the volume of my audio. however, it is not working. What I am doing wrong?

```python
from pydub import AudioSegment
source1 = path + "phone1.wav"
song = AudioSegment.from_wav(source1)

#reduce volume by 10 dB
song_10_db_quierter = song - 10

#but let's make him *very* quiet
song = song - 60

#save the output
song.export(path+"quieter.wav", "wav")
fs, out = wavfile.read(path+ "quieter.wav")
Audio(data=out,rate = fs)
```

I am getting the same volume as original when playing it using python.audio. however the files have lower volume. My ideal case will be the following:
source1 = path + "phone1.wav"
fs, audio = wavfile.read(source1)
then on my numpy array apply the reduction in volume. can i do this?

**Comment by jiaaro** [comment]
I'm not sure why you are not getting the expected result - partly due to unfamiliarity with some of the other modules you are using. However, your original code example could be written more simply like this (which I tested and it works):

```python
from pydub import AudioSegment

song = AudioSegment.from_wav("phone1.wav")

# let's make it *very* quiet
song = song - 60

quieter_song_data = song.get_array_of_samples()
quieter_song_fs = song.frame_rate
```

Reducing the volume of an audio signal is (roughly speaking) just changing the amplitude, but the specific mathematical operation depends on how the audio is encoded. Some formats use signed values so you can simple multiply by some value (like `0.5`), other formats use unsigned values so you need to get a little fancy to avoid adding a DC bias to the signal. That's kinda why pydub exists ;)

**Comment by jiaaro** [comment]
It's be (well) over a month, closing. Will re-open if we get more info
