### ISSUE TITLE
API clarification

### ISSUE THREAD

**Issue by webtech1980** [jiaaro/pydub#150]
In your documentation you show how to segment a file to get the beginning and end.

# first 5 seconds of sound1
beginning = sound1[:5000]

# last 5 seconds of sound1
end = sound1[-5000:]

But what's the syntax to get a segment somewhere in the middle. Like from 1;15;0000 to 1;30;0000 within a file. Where sequence goes minutes;seconds;milliseconds

**Comment by zovaaa** [comment]
To get a segment between any given beginning 'i' and end 'j' you can use pythons' slicing:
`segment = sound[i:j]`
so that the middle from the documentation would be
`middle = sound1[5000:-5000]`
I think you have to convert the 1;15;0000 and 1;30;0000 to milliseconds manually though.

A note, it doesnt use the 'skip' part of the slicing (i.e. `sound1[i:j:k] == sound1[i:j], `), which makes sense but something to remember.

**Comment by webtech1980** [comment]
Awesome, thanks for the help. For any one interested here's a snippet.

    from pydub import AudioSegment

    sound = AudioSegment.from_mp3("/home/kahless/Desktop/Mastery_end.mp3")
    duration = len(sound)
    startTime = 1000*19.69
    endTime = 1000*34.489999999999995 - duration;
    clip = sound[startTime:endTime]
    clip.export("/home/kahless/Desktop/clip.mp3", format="mp3")
