### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by florianbachmann** [jiaaro/pydub#162]
Just out of curiosity, 
are you able to provide a high level changelog.md file? (it doesn't have to be as detailed as http://aiohttp.readthedocs.io/en/stable/changes.html), but maybe for the only for MAJOR & MINOR changes (PATCH changes don't need to be mentioned)

or could you say what changed between, e.g. 0.9.0 and 0.16.6
(I know it is more than a two year gap, as seen here: https://libraries.io/pypi/pydub/versions but I'm still curious)

thanks a lot
and best regards
flori

**Comment by jiaaro** [comment]
I'm for it - I'll try to find time to do this

**Comment by jiaaro** [comment]
Work in progress follows…

# v0.10.0
- Overhaul Documentation
- Add `pydub.AudioSegment.invert_phase()` which (shocker) inverts the phase of an audio segment
- Fix a type error in `pydub.AudioSegment.get_sample_slice()`

### v0.9.5
- Add `pydub.generators` module containing simple signal generation functions (white noise, sine, square wave, etc)
- Add a `loops` keyword argument to `AudioSegment.overlay()` which allows users to specify that the overlaid audio should be repeated (i.e., looped) a certain number of times, or indefinitely

### 0.9.4
- Fix a bug in db_to_float() where all values were off by a factor of 2

### 0.9.3
- Allow users to set the location of their converter by setting `pydub.AudioSegment.converter = "/path/to/ffmpeg"` and added a shim to support the old method of assigning to `pydub.AudioSegment.ffmpeg` (which is deprecated now that we support avconv)

### v0.9.2
- Add support for Python 3.4
- Audio files opened with format "wave" are treated as "wav" and "m4a" are treated as "mp4"
- Add `pydub.silence` module with simple utilities for detecting and removing silence.
- Fix a bug affecting auto-detection of ffmpeg/avconv on windows.
- Fix a bug that caused pydub to only work when ffmpeg/avconv is present (it should be able to work with WAV data without any dependencies)

### v0.9.1
- Add a runtime warning when ffmpeg/avconv cannot be found to aid debugging

# v0.9.0
- Added support for pypy (by reimplementing audioop in python). Also, we contributed our implementation to the pypy project, so that's 💯 
- Add support for avconv as an alternative to ffmpeg
- Add a new helper module `pydub.playback` which allows you to quickly listen to an audio segment using ffplay (or avplay) 
- Add new function `pydub.utils.mediainfo('/path/to/audio/file.ext')` which reports back the results of ffprobe (or avprobe) including codec, bitrate, channels, etc
