### ISSUE TITLE
Relationship to PyAV

### ISSUE THREAD

**Issue by Lapin0t** [jiaaro/pydub#176]
The title pretty much says it all. It must admit that i don't really like when python libraries are using shell tools and all the subprocess pipe machinery as a backend instead of just writing a small binding to the underlying C library. [PyAV](https://github.com/mikeboers/PyAV) is a binding to ffmpeg using cython (also trying to make a pythonic wrapper), did you know about it? It may not have the exact same scope (as libav also does a bunch of video besides audio).

**Comment by jiaaro** [comment]
There are a few factors that went into using subprocess rather than linking libav/libffmpeg 

1. It's simpler to debug, the avconv/ffmpeg commands can be accessed and run manually to dig in to problems and figure out what's going on.
2. Pydub doesn't have any hard dependencies. It will read/write WAVE files without assistance and everything works fine. libav/ffmpeg is only used in isolated places.
3. Unlike many other uses, shelling out to the converter is not a significant performance overhead because of how long encoding/decoding audio streams takes. A millisecond is forever in most applications but if decoding an mp3 takes 150ms (common), who cares about 1ms overhead to shell out to ffmpeg?

Having said all that, since the converter is isolated, I wouldn't be opposed to adding a way for users to use a binding rather than the subprocess-based import/export machinery, as long as it didn't break anything existing users 😄
