### ISSUE TITLE
Length of sum of segments different from sum of lengths

### ISSUE THREAD

**Issue by marciomazza** [jiaaro/pydub#208]
**Certain sums of AudioSegments end up with wrong lengths.**

I have no clue why.

Here is a code snippet that spots that:
```python
l = Sine(440).to_audio_segment(100)
s = AudioSegment.silent(100)
segments = [s,l,s,s,s,s]
print(len(sum(segments)), sum(map(len, segments)))

# outputs (599, 600)

```
And here is a more comprehensive one, that tries product combinations up to length 7 of those 2 segments. The issue manifests only with some very specific combinations, only from length 6 on:
```python
from itertools import product

from pydub import AudioSegment
from pydub.generators import Sine

l = Sine(440).to_audio_segment(100)
s = AudioSegment.silent(100)

problems = []
for i in range(2, 8):
    for segments in product(* ((l, s),) * i):
        if len(sum(segments)) != sum(map(len, segments)):
            problems.append(segments)

for segments in problems:
    print(''.join([{l: 'l ', s: 's '}[au]
                   for au in segments]),
          len(sum(segments)), sum(map(len, segments)))
```
That outputs
```
('l s s s s s ', 599, 600)
('s l s s s s ', 599, 600)
('l l s s s s s ', 699, 700)
('l s l s s s s ', 699, 700)
('l s s l s s s ', 699, 700)
('l s s s l s s ', 699, 700)
('l s s s s l s ', 699, 700)
('l s s s s s l ', 699, 700)
('l s s s s s s ', 699, 700)
('s l l s s s s ', 699, 700)
('s l s l s s s ', 699, 700)
('s l s s l s s ', 699, 700)
('s l s s s l s ', 699, 700)
('s l s s s s l ', 699, 700)
('s l s s s s s ', 699, 700)
('s s l s s s s ', 699, 700)
('s s s l s s s ', 699, 700)
```

**Comment by jiaaro** [comment]
Thanks for your contributions - I've been out of town for a few days but I'll take a look soon :)

**Comment by jiaaro** [comment]
In short: this happens because Silence is created at a low sample rate and bit depth (since it can be safely upsampled, etc). But not all sample rates cleanly convert to all others the frame_rate conversion can lead to rounding errors (in the number of samples) that pile up.

Silence is generated at 11025 samples per second (by default), so 100ms of silence is 1102.5 samples long. The last half a sample is tossed.

The easiest way to avoid it is (unfortunately) to specify the sample rate (i.e., frame rate) when you generate the silence.

```python
from itertools import product

from pydub import AudioSegment
from pydub.generators import Sine

l = Sine(440).to_audio_segment(100)
s = AudioSegment.silent(100, frame_rate=l.frame_rate)
```
