### ISSUE TITLE
How to slow down  audio

### ISSUE THREAD

**Issue by XueWei** [jiaaro/pydub#213]
Hi, 
Does anyone know how to slow down audio? I can only find speedup() function, When I teied pass in the speed rate less than 1.0, it doesn't work.

**Comment by Tsao666** [comment]
Hi,
I think [this](https://stackoverflow.com/questions/43408833/how-to-increase-decrease-playback-speed-on-wav-file) will help you, I just solved this on python 3.6.

**Comment by AbbyYangbb** [comment]
Well, the solution offered in the link doesn't work as a reverse function as ```speedup```, since it changes the speed as well as **pitch**.

**Comment by Exr0n** [comment]
Is this still active? I just want to note that I have this issue too. Would be nice to know if someone were working on it. :)

**Comment by jiaaro** [comment]
Slowing down audio is tricky because you have to create additional audio that didn't exist before (usually by reusing audio from the original source material). 

There's a [solution suggested on stack overflow](https://stackoverflow.com/questions/51434897/how-to-change-audio-playback-speed-using-pydub) that may work for you or those finding this page on google though :)
