### ISSUE TITLE
How to use pydub to compose one song based on MIDI file and number files?

### ISSUE THREAD

**Issue by xsren** [jiaaro/pydub#240]
HI! I have used pydub in my past project, and it worked great! 

Currently I have one new task, but I dont know how to do it, I hope u can give me some suggestions.

###### Prerequisite:
I have 10 wav files which map numbers from 0 to 9, for example **0.wav** sounds **0**, and they all in C3 and 60bpm. Also I have a midi file and corresponding wav file(I call this **melody file**). 

###### What I want to do:
*  When people input a series of number(123 for example), I combine them (1.wav 2.wav and 3.wav ) to one wav file (I call this **numbers file**) by pydub. 
* Then I want to combine **numbers file** and **melody file** to one song. Meanwhile  **numbers file** should by modified based on midi file to have same rhythm with **melody file**.

What my question is how to achieve " **numbers file** should by modified based on midi file to have same rhythm with **melody file** " by pydub?

Hope u can help me.

Thank u for your great job.

**Comment by jiaaro** [comment]
The easiest way to do this is to implement it like a sampler – just play the files at different speeds to alter the pitch:

You can change the playback speed like this:

```pydub
from pydub import AudioSegment

# Samples are is C4, we'll play it back as an E4
# MIDI note numbers from: https://www.midikits.net/midi_analyser/midi_note_numbers_for_octaves.htm
START_NOTE = 60
NEW_NOTE = 64

semitone_change = NEW_NOTE - START_NOTE

# 2.0 because an octave is a doubling frequency. 
# 12.0 because there are 12 semitones per octave
speed_multiplier = 2.0 ** (semitone_change / 12.0)

sound = AudioSegment.from_file("1.wav")
speed_changed_sound_with_weird_frame_rate = sound._spawn(sound.raw_data, overrides={
    'frame_rate': sound.frame_rate * speed_multiplier
})

# now we convert the pitch shifted sound to a standard frame rate that audio 
# players know how to play
pitch_shifted_sound = speed_changed_sound_with_weird_frame_rate.set_frame_rate(sound.frame_rate)
```

This technique works best when the samples you're playing (the wav files at C4) are much longer than any of the notes in the song. For higher notes the sounds will be shorter and for lower notes, longer (because we achieve the pitch shift by simply playing the sound back at a different speed)

**Comment by jiaaro** [comment]
Oh you may also be interested in [this gist I wrote a long time ago for reading a midi file and generating an audio file with pydub's Sine wave generator](https://gist.github.com/jiaaro/339df443b005e12d6c2a) - you could pretty easily expand on this script to use your sampler instead of generating wave files

**Comment by xsren** [comment]
Thanks very much.
