### ISSUE TITLE
Exporting and reloading audio example as MP3 increases its original length

### ISSUE THREAD

**Issue by hesseltuinhof** [jiaaro/pydub#474]
When loading a local WAV audio file and exporting and reloading it as MP3 will increase the original length of the sample. I am wondering what is the underlying issue causing the increased length :thinking:

---

### Steps to reproduce

The following script provides an example to reproduce the issue. It will create a local WAV file and write it locally. Then use `pydub` to load the audio file and export and reload as MP3 using first a byte stream and second using the local file system. 

```python3
#!/usr/bin/env python

from io import BytesIO

import numpy as np
import pydub
from scipy.io.wavfile import write

# create synthetic data
samplerate = 8000
fs = 100
t = np.linspace(0., 1., samplerate).reshape((-1, 1))
amplitude = np.iinfo(np.int16).max
data = (amplitude * np.sin(2. * np.pi * fs * t)).astype(np.int16)

# write wav file
write("tmp.wav", samplerate, data)

# use BytesIO
tmp_mp3 = BytesIO()
pydub.AudioSegment.from_wav("tmp_wav.wav").export(tmp_mp3)
byte_loaded = pydub.AudioSegment.from_mp3(tmp_mp3)
byte_loaded = np.array(byte_loaded.get_array_of_samples(), dtype=np.int16).reshape((-1, 1))

print("WAV to MP3 using 'BytesIO':")
if byte_loaded.shape == data.shape:
    print("\t[OK] Shapes match")
else:
    print("\t[Failed] Shapes don't match")
print(f"\tShape original: {data.shape}")
print(f"\tShape compressed: {byte_loaded.shape}")

# use local file system
pydub.AudioSegment.from_wav("tmp.wav").export("tmp.mp3")
byte_loaded = pydub.AudioSegment.from_mp3("tmp.mp3")
byte_loaded = np.array(byte_loaded.get_array_of_samples(), dtype=np.int16).reshape((-1, 1))

print("WAV to MP3 using local file system:")
if byte_loaded.shape == data.shape:
    print("\t[OK] Shapes match")
else:
    print("\t[Failed] Shapes don't match")
print(f"\tShape original: {data.shape}")
print(f"\tShape compressed: {byte_loaded.shape}")
```

The above script will output:
```
$ python example.py 
WAV to MP3 using 'BytesIO':
	[Failed] Shapes don't match
	Shape original: (8000, 1)
	Shape compressed: (8111, 1)
WAV to MP3 using local file system:
	[OK] Shapes match
	Shape original: (8000, 1)
	Shape compressed: (8000, 1)
```

### Expected behavior

The length of the original and compressed MP3 audio file should stay the same.

### Actual behavior

The length of the compressed MP3 audio file increases compared to the original.

### Your System configuration
- Python version: 3.6.10
- Pydub version: 0.23.1
- ffmpeg version: 4.2.2

### Is there an audio file you can include to help us reproduce?

The script to reproduce the problem creates synthetic audio data and saves it locally as WAV file.

**Comment by GreyAlien502** [comment]
@hesseltuinhof, thanks for providing such a complete report;
it made this very easy to handle.

I found that the discrepancy appears when using the latest released version of pydub (from ```pip install pydub```),
but not when using the current code in this repository.
Thus, it seems that this bug has been resolved by some commit since the last release (on 2019-01-22),
and to fix the bug, we just need to publish to PyPI the code currently in this repository.
If you need to access the working code now, you can install pydub from this repository as follows:
```bash
pip install --upgrade git+https://github.com/jiaaro/pydub.git@master
```

@jiaaro, i will submit a pull request to summarize the changes made since v0.23.1 and bump the version to v0.24.0,
and then can you review it and upload to PyPI?
If something else needs to happen please let me know.

N.B. in the future, it probably would be more convenient to add to the changelog as each new feature/fix is added.

**Comment by GreyAlien502** [comment]
I'm closing this cause the working code is released now.
