### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by anyong** [jiaaro/pydub#89]
I'm not sure if this is related to the other memory related issue, but that one has to do with long files and mine has to do with many small files.

Essentially, I'm making a list of sets of audio files to concatenate, there's a few thousand small audio files (typically 2-5 seconds long) that get combined in different ways into audio files that are about 20-30 minutes at most, and the memory needed for any one of these ouput files is pretty small. I'm generating about half of these output files with no issues at all, but then python gives a MemoryError and crashes. The error happens in audio_segment.py append method on returning the call to _spawn. Using Python 3.4 on Windows 8 x64.

**Comment by jiaaro** [comment]
well, ultimately pydub keeps all the audio data in memory - There has been talk to doing operations using disk-backed data objects rather than memory-backed ones, but this hasn't been written (and frankly is probably going to be a lot of work). 

The easiest solution is of course to just have more RAM. If you have another machine available with more RAM that may solve the solution "for free". You may also be able to free up RAM by killing other applications running on the machine.

_spawn creates a new object, so it makes sense that it would be the place to run out of RAM.

## possible solution:

If you're generating lots of 20 to 30 minute output files, those are going to be pretty big `AudioSegment` objects. So in the interest of not running out of RAM, you want to let them get garbage collected as soon as you can. I haven't seen your code, but I'd try exporting the output to disk and destroying the output object right away

```python
# I assume you're making lots of big files by iterating somehow
for _ in range(1000):
    long_sound = my_long_audio_segment_generator()
    long_sound.export("filename.wav", format='wav')
    
    # Optionally destroy the object and force the garbage collector to run
    import gc
    del long_sound
    gc.collect()
```

**Comment by anyong** [comment]
Thanks, I will try the manual garbage collection and see if that works.
