### ISSUE TITLE
Method to extract of mp3 files as a byte stream

### ISSUE THREAD

**Issue by kushal-sharma** [jiaaro/pydub#99]
First of all, I wish to say that pydub project is a very clean library in that the high level functions are very intuitive.
Consider the following use case- I want to get a sample of the mp3 file specified with start_time and end_time in milliseconds.Would it be possible to return the data of mp3 files directly as a byte stream so that it can interface well with other Mp3 Libraries rather writing it first to disk and then read it as a byte stream using Python open() or os module. This is because the AudioSegment data structure is not available elsewhere other than Pydub itself.
Such a feature would help to use the library to serve mp3 files over the web easily as it can then interface well with Python frameworks like Django.

**Comment by jiaaro** [comment]
You can pass in a file-like object to .export() such as StringIO if you prefer,  but you should know that internally pydub will still create a temporary file on disk (which is given to ffmpeg as path to store output when transcoding). ffmpeg *does* support sending output to stdout, but this behavior is not as reliable, which is why pydub doesn't use it.


Anyway does this help?



import pydub


import StringIO






sound = pydub.AudioSegment.from_file(…)




output = StringIO.StringIO()

sound.export(output, format="mp3")







James

**Comment by kushal-sharma** [comment]
No it does not work. StringIO objects cannot be written onto a Django
HttpResponse object. I tested this method on django as it was the most
widely used framework.

**Comment by jiaaro** [comment]
This Stack Overflow question illustrates how to send a file or StringIO via Django HttpResponse :)




http://stackoverflow.com/questions/13656831/how-to-stream-file-to-client-in-django
